# Generated by Django 4.1.2 on 2022-11-18 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variable_Math',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('variable', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Variable_Phy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('variable', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Formula_Phy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=20)),
                ('result', models.ManyToManyField(related_name='product', to='formulary.variable_phy')),
                ('using', models.ManyToManyField(related_name='requierd', to='formulary.variable_phy')),
            ],
        ),
        migrations.CreateModel(
            name='Formula_Math',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=20)),
                ('result', models.ManyToManyField(related_name='product', to='formulary.variable_math')),
                ('using', models.ManyToManyField(related_name='requierd', to='formulary.variable_math')),
            ],
        ),
        migrations.CreateModel(
            name='Category_Phy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.formula_phy')),
            ],
        ),
        migrations.CreateModel(
            name='Category_Math',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.formula_math')),
            ],
        ),
    ]
