# Generated by Django 4.1.2 on 2022-11-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_math',
            name='category',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category_phy',
            name='category',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='category_math',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='category_phy',
            name='formula',
        ),
        migrations.AddField(
            model_name='category_math',
            name='formula',
            field=models.ManyToManyField(related_name='category_math', to='formulary.formula_phy'),
        ),
        migrations.AddField(
            model_name='category_phy',
            name='formula',
            field=models.ManyToManyField(related_name='category_phy', to='formulary.formula_phy'),
        ),
    ]
