# Generated by Django 4.1.2 on 2022-11-24 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=20)),
                ('math', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.category')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=5)),
                ('description', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='category_phy',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='formula_math',
            name='result',
        ),
        migrations.RemoveField(
            model_name='formula_math',
            name='using',
        ),
        migrations.RemoveField(
            model_name='formula_phy',
            name='result',
        ),
        migrations.RemoveField(
            model_name='formula_phy',
            name='using',
        ),
        migrations.DeleteModel(
            name='Category_Math',
        ),
        migrations.DeleteModel(
            name='Category_Phy',
        ),
        migrations.DeleteModel(
            name='Formula_Math',
        ),
        migrations.DeleteModel(
            name='Formula_Phy',
        ),
        migrations.DeleteModel(
            name='Variable_Math',
        ),
        migrations.DeleteModel(
            name='Variable_Phy',
        ),
        migrations.AddField(
            model_name='formula',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='product', to='formulary.variable'),
        ),
        migrations.AddField(
            model_name='formula',
            name='using',
            field=models.ManyToManyField(blank=True, related_name='using', to='formulary.variable'),
        ),
    ]
