# Generated by Django 4.1.2 on 2022-11-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0002_formula_variable_remove_category_phy_formula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='math',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='formula',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='product', to='formulary.variable'),
        ),
        migrations.AlterField(
            model_name='formula',
            name='using',
            field=models.ManyToManyField(blank=True, related_name='using', to='formulary.variable'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
