# Generated by Django 4.1.2 on 2022-11-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0002_category_formula_variable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='products', to='formulary.variable'),
        ),
        migrations.AlterField(
            model_name='formula',
            name='using',
            field=models.ManyToManyField(blank=True, related_name='uses', to='formulary.variable'),
        ),
    ]
