# Generated by Django 4.1.2 on 2022-11-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0002_category_math_category_category_phy_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_math',
            name='formula',
            field=models.ManyToManyField(related_name='category_math', to='formulary.formula_math'),
        ),
    ]
