# Generated by Django 4.1.2 on 2022-11-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0003_alter_category_math_formula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_phy',
            name='formula',
        ),
        migrations.DeleteModel(
            name='Category_Math',
        ),
        migrations.DeleteModel(
            name='Category_Phy',
        ),
    ]
