# Generated by Django 4.1.2 on 2022-11-23 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0005_category_alter_formula_math_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula_math',
            name='category',
        ),
        migrations.RemoveField(
            model_name='formula_phy',
            name='category',
        ),
    ]
