# Generated by Django 4.1.3 on 2022-11-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0005_variable_contains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='formula',
            field=models.CharField(max_length=50),
        ),
    ]
