# Generated by Django 4.1.3 on 2022-11-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0006_alter_formula_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tag',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
