# Generated by Django 4.1.2 on 2022-11-23 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0006_remove_formula_math_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula_math',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_math', to='formulary.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formula_phy',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_phy', to='formulary.category'),
            preserve_default=False,
        ),
    ]
