# Generated by Django 4.1.2 on 2022-11-23 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0007_formula_math_category_formula_phy_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula_math',
            name='category',
        ),
        migrations.RemoveField(
            model_name='formula_phy',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
