# Generated by Django 4.1.3 on 2022-12-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0007_category_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='contains',
        ),
        migrations.AlterField(
            model_name='variable',
            name='variable',
            field=models.CharField(max_length=20),
        ),
    ]
