# Generated by Django 4.1.3 on 2022-12-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0009_formula_description_alter_variable_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='variable',
            field=models.CharField(max_length=20),
        ),
    ]
